// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'core_data_model.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$CoreDataModelImpl _$$CoreDataModelImplFromJson(Map<String, dynamic> json) =>
    _$CoreDataModelImpl(
      status: json['status'] as String?,
      data:
          (json['data'] as List<dynamic>?)
              ?.map((e) => Datum.fromJson(e as Map<String, dynamic>))
              .toList(),
      code: json['code'] as String?,
    );

Map<String, dynamic> _$$CoreDataModelImplToJson(_$CoreDataModelImpl instance) =>
    <String, dynamic>{
      'status': instance.status,
      'data': instance.data,
      'code': instance.code,
    };

_$DatumImpl _$$DatumImplFromJson(Map<String, dynamic> json) => _$DatumImpl(
  id: json['id'] as String?,
  siteurl: json['siteurl'] as String?,
  version: json['version'] as String?,
  appVersion: json['app_version'] as String?,
  siteTitle: json['site_title'] as String?,
  siteDescription: json['site_description'] as String?,
  metaKeyword: json['meta_keyword'] as String?,
  metaDetails: json['meta_details'] as String?,
  logo: json['logo'] as String?,
  minLogo: json['min_logo'] as String?,
  favIcon: json['fav_icon'] as String?,
  webLogo: json['web_logo'] as String?,
  appLogo: json['app_logo'] as String?,
  address: json['address'] as String?,
  siteEmail: json['site_email'] as String?,
  whatsappNo: json['whatsapp_no'] as String?,
  sendgridApi: json['sendgrid_API'] as String?,
  googleApi: json['google_API'] as String?,
  ifFirebase: json['if_firebase'] as String?,
  firebaseConfig: json['firebase_config'] as String?,
  firebaseApi: json['firebase_API'] as String?,
  codStatus: json['cod_status'] as String?,
  bankTransferStatus: json['bank_transfer_status'] as String?,
  razorpayStatus: json['razorpay_status'] as String?,
  razoKeyId: json['razo_key_id'] as String?,
  razoKeySecret: json['razo_key_secret'] as String?,
  ccavenueStatus: json['ccavenue_status'] as String?,
  ccavenueTestmode: json['ccavenue_testmode'] as String?,
  ccavenueMerchantId: json['ccavenue_merchant_id'] as String?,
  ccavenueAccessCode: json['ccavenue_access_code'] as String?,
  ccavenueWorkingKey: json['ccavenue_working_key'] as String?,
  ifPhonepe: json['if_phonepe'] as String?,
  phonepeMerchantId: json['phonepe_merchantId'] as String?,
  phonepeSaltkey: json['phonepe_saltkey'] as String?,
  phonepeMode: json['phonepe_mode'] as String?,
  ifOnesignal: json['if_onesignal'] as String?,
  onesignalId: json['onesignal_id'] as String?,
  onesignalKey: json['onesignal_key'] as String?,
  smtpHost: json['smtp_host'] as String?,
  smtpPort: json['smtp_port'] as String?,
  smtpUsername: json['smtp_username'] as String?,
  smtpPassword: json['smtp_password'] as String?,
  ifMsg91: json['if_msg91'] as String?,
  msg91Apikey: json['msg91_apikey'] as String?,
  ifTextlocal: json['if_textlocal'] as String?,
  textlocalApikey: json['textlocal_apikey'] as String?,
  smsSenderid: json['sms_senderid'] as String?,
  smsDltid: json['sms_dltid'] as String?,
  smsMsg: json['sms_msg'] as String?,
  ifAgora: json['if_agora'] as String?,
  agoraAppid: json['agora_appid'] as String?,
  ifZigocloud: json['if_zigocloud'] as String?,
  zigocloudAppId: json['zigocloud_app_id'] as String?,
  zigocloudAppSignin: json['zigocloud_app_signin'] as String?,
  maintenanceMode: json['maintenance_mode'] as String?,
);

Map<String, dynamic> _$$DatumImplToJson(_$DatumImpl instance) =>
    <String, dynamic>{
      'id': instance.id,
      'siteurl': instance.siteurl,
      'version': instance.version,
      'app_version': instance.appVersion,
      'site_title': instance.siteTitle,
      'site_description': instance.siteDescription,
      'meta_keyword': instance.metaKeyword,
      'meta_details': instance.metaDetails,
      'logo': instance.logo,
      'min_logo': instance.minLogo,
      'fav_icon': instance.favIcon,
      'web_logo': instance.webLogo,
      'app_logo': instance.appLogo,
      'address': instance.address,
      'site_email': instance.siteEmail,
      'whatsapp_no': instance.whatsappNo,
      'sendgrid_API': instance.sendgridApi,
      'google_API': instance.googleApi,
      'if_firebase': instance.ifFirebase,
      'firebase_config': instance.firebaseConfig,
      'firebase_API': instance.firebaseApi,
      'cod_status': instance.codStatus,
      'bank_transfer_status': instance.bankTransferStatus,
      'razorpay_status': instance.razorpayStatus,
      'razo_key_id': instance.razoKeyId,
      'razo_key_secret': instance.razoKeySecret,
      'ccavenue_status': instance.ccavenueStatus,
      'ccavenue_testmode': instance.ccavenueTestmode,
      'ccavenue_merchant_id': instance.ccavenueMerchantId,
      'ccavenue_access_code': instance.ccavenueAccessCode,
      'ccavenue_working_key': instance.ccavenueWorkingKey,
      'if_phonepe': instance.ifPhonepe,
      'phonepe_merchantId': instance.phonepeMerchantId,
      'phonepe_saltkey': instance.phonepeSaltkey,
      'phonepe_mode': instance.phonepeMode,
      'if_onesignal': instance.ifOnesignal,
      'onesignal_id': instance.onesignalId,
      'onesignal_key': instance.onesignalKey,
      'smtp_host': instance.smtpHost,
      'smtp_port': instance.smtpPort,
      'smtp_username': instance.smtpUsername,
      'smtp_password': instance.smtpPassword,
      'if_msg91': instance.ifMsg91,
      'msg91_apikey': instance.msg91Apikey,
      'if_textlocal': instance.ifTextlocal,
      'textlocal_apikey': instance.textlocalApikey,
      'sms_senderid': instance.smsSenderid,
      'sms_dltid': instance.smsDltid,
      'sms_msg': instance.smsMsg,
      'if_agora': instance.ifAgora,
      'agora_appid': instance.agoraAppid,
      'if_zigocloud': instance.ifZigocloud,
      'zigocloud_app_id': instance.zigocloudAppId,
      'zigocloud_app_signin': instance.zigocloudAppSignin,
      'maintenance_mode': instance.maintenanceMode,
    };
